### ISSUE TITLE
Make lenses for Tuple{N}

### ISSUE THREAD

**Issue by catostrophe** [tofu-tf/glass#5]
Let `tofu-optics` users do this:
```scala
import tofu.optics.syntax.tupleN._

val lense = Tuple3._2[Int, String, Long]   // : Contains[(Int, String, Long), String]
```

`tupleN` object should contain all possible implicit extensions to Tuple{N} companion objects. Implementations should be macro generated.

**Comment by catostrophe** [comment]
P.S. Syntax object name and location are to be refined soon.

**Comment by colps** [comment]
Hello @catostrophe ,

I would like to help with this issue. Sample solution below. The usage is slightly different to what is suggested above but that can be changed.  
```scala

object TupleN {

  class Tuple2[T1, T2] {
    def _1: Contains[(T1, T2), T1] = GenContains[(T1, T2)].apply(_._1)
    def _2: Contains[(T1, T2), T2] = GenContains[(T1, T2)].apply(_._2)
  }

  object Tuple2 {
    def apply[T1, T2] = new Tuple2[T1, T2]()
  }

  val lens: Contains[(String, Int), Int] = Tuple2[String, Int]._2
}
```
Can you explain what you meant by _Implementations should be macro generated_? Did you mean we should use GenContains macro as shown above or we should use macros to generate the above code for Tuple{N} ?  Thanks
